spring:
  datasource:
    url: postgresql://postgres:BBhaGgPOKYiYfyZTBejNYQabcyJUyiDw@mainline.proxy.rlwy.net:45010/railway
    username: postgres
    password: BBhaGgPOKYiYfyZTBejNYQabcyJUyiDw
  jpa:
    hibernate:
      ddl-auto: update # Creates tables automatically
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
